"""
Card layout constants for positioning and sizing elements.

All position and size constants used for rendering MTG card images.
Positions are (x, y) tuples in pixels, sizes are in pixels.
"""

# Position constants - where elements are placed on the card
POSITION_CARD_NAME = (66, 77)
POSITION_CARD_TYPE = (66, 609)
POSITION_TOKEN_CARD_TYPE = (66, POSITION_CARD_TYPE[1] + 115)
POSITION_SAGA_CARD_TYPE = (66, POSITION_CARD_TYPE[1] + 295)
POSITION_RULES_TEXT = (70, 649)
POSITION_TOKEN_RULES_TEXT = (70, POSITION_RULES_TEXT[1] + 110)
POSITION_SAGA_RULES_TEXT = (97, 306)
POSITION_SET_SYMBOL = (634, 593)
POSITION_TOKEN_SET_SYMBOL = (634, POSITION_SET_SYMBOL[1] + 115)
POSITION_SAGA_SET_SYMBOL = (634, POSITION_SET_SYMBOL[1] + 295)
POSITION_POWER = (610, 947)
POSITION_TOUGHNESS = (651, 947)
POSITION_MANA_SYMBOL = (648, 61)
POSITION_FLAVOR_LINE = (82, None)
POSITION_SAGA_LINE = (84, None)
POSITION_SAGA_NUM_CHAPTERS = (250, 232)
POSITION_SAGA_CHAPTER_SYMBOLS = (31, None)

# Maximum height/width constraints for text and elements
MAX_HEIGHT_CARD_NAME = 44.5
MAX_HEIGHT_CARD_TYPE = 37.5
MAX_FONT_SIZE_RULES_TEXT_LETTERS = 37
MAX_HEIGHT_RULES_TEXT_BOX = 280
MAX_HEIGHT_TOKEN_RULES_TEXT_BOX = 165
MAX_HEIGHT_SAGA_RULES_TEXT_BOX = 537
MAX_WIDTH_RULES_TEXT_BOX = 596
MAX_WIDTH_SAGA_RULES_TEXT_BOX = 255
MAX_WIDTH_CARD_NAME = 575
MAX_WIDTH_CARD_TYPE = 567
MAX_HEIGHT_POWER_TOUGHNESS = 39

# Card dimensions
CARD_WIDTH = 744
CARD_HEIGHT = 1039

# Symbol sizes
SET_SYMBOL_SIZE = 40
MANA_SYMBOL_SIZE = 37
SPECIAL_SYMBOL_SIZE = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
